Repository tobedecided-at/tbd, pull requests merged in 2018-11, with the labels that each got.

#9 Splashscreen
  Assets/Background/logo
  Assets/Background/logo.meta
  Assets/Background/logopng.png
  Assets/Background/logopng.png.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/MainMenu.unity.meta
  ProjectSettings/ProjectSettings.asset
Labels: feature, needs changes

#30 Added fox torch wood and wood plank
  Assets/Entities/Map/Models/fox.fbx
  Assets/Entities/Map/Models/torch.fbx
  Assets/Entities/Map/Models/wood.fbx
  Assets/Entities/Map/Models/wood_plank.fbx
Labels: feature, merged

#36 Hud
  Assets/AssetStore/Internet.meta
  Assets/AssetStore/Internet/UnityForum-381000.meta
  Assets/AssetStore/Internet/UnityForum-381000/numbers.png
  Assets/AssetStore/Internet/UnityForum-381000/numbers.png.meta
  Assets/Entities/Items/ItemHolder.prefab
  Assets/Entities/Items/ItemSpawn.prefab
  Assets/Entities/Player/Default.prefab
  Assets/Libraries.meta
  Assets/Libraries/tbd-dll.meta
  Assets/Libraries/tbd-dll/_data.meta
  Assets/Libraries/tbd-dll/bin.meta
  Assets/Libraries/tbd-dll/cs.csproj.meta
  Assets/Libraries/tbd-dll/obj.meta
  Assets/Materials/Floor.mat
  Assets/Scenes/Sandbox.unity
  Assets/Scripts/Classes/Item.cs
  Assets/Scripts/Classes/ItemDb.cs
  Assets/Scripts/Classes/PauseUI.cs
  Assets/Scripts/Classes/TBDBootstrap.cs
  Assets/Scripts/Classes/TBDSettings.cs
  Assets/Scripts/Components/Damaged.cs
  Assets/Scripts/Components/PlayerInput.cs
  Assets/Scripts/MonoBehavior/HUD.cs
  Assets/Scripts/MonoBehavior/HUD.cs.meta
  Assets/Scripts/Systems/InventoryUISystem.cs
  Assets/Scripts/Systems/PauseSystem.cs
  Assets/Scripts/Systems/PlayerHUDSystem.cs
  Assets/Scripts/Systems/PlayerHUDSystem.cs.meta
  Assets/Scripts/Systems/PlayerHealthSystem.cs
  Assets/Scripts/Systems/PlayerHealthSystem.cs.meta
  Assets/Scripts/Systems/PlayerInputSystem.cs
  Assets/StreamingAssets/json/Items/test.tbd
  DEBUGKEYS.md
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/TagManager.asset
Labels: feature
